#!/bin/bash

echo "********************************"
echo "* processing cat_unwarped.fits *"
echo "********************************"
processFile.py star_grid_unwarped_oversamp_010.fits \
    --outputCatalog cat_unwarped_oversamp_010.fits \
    --verbose --config variance=-1 edgeRolloff.applyModel=False

echo "****************************"
echo "* processing cat_warp.fits *"
echo "****************************"
processFile.py star_grid_warped_overamp_010.fits \
    --outputCatalog cat_warp_oversamp_010.fits \
    --verbose --config variance=-1 edgeRolloff.applyModel=False

echo "************************************"
echo "* processing cat_warp_modeled.fits *"
echo "************************************"
processFile.py star_grid_warped_overamp_010.fits \
    --outputCatalog cat_warp_modeled_oversamp_010.fits \
    --verbose --config variance=-1 --configfile config/edgerolloff_config.py
